### ISSUE TITLE
UI issue for different android devices.

### ISSUE THREAD

**Issue by yangray1** [yangray1/Anti-Scam-Detector#3]
**Problem:** So when this app is ran on the Pixel 2 API 28 device, everything works fine, all the buttons and labels are where they're suppose to be. BUT, when I try it on another device, such as the Nexus 5 API 28, the UI looks completely out of place and sometimes buttons aren't clickable.

**Task:** Possibly help find a way to fix this issue!

Pixel 2 API 28 device: 
<img width="314" alt="Screen Shot 2019-10-07 at 3 38 26 AM" src="https://user-images.githubusercontent.com/39708793/66293129-fa70d780-e8b3-11e9-92f9-039735e768db.png">

Nexus 5 API 28 device:
<img width="327" alt="Screen Shot 2019-10-07 at 3 38 32 AM" src="https://user-images.githubusercontent.com/39708793/66293130-fa70d780-e8b3-11e9-8f3e-1f67e78f4e43.png">

**Comment by NayakNavin** [comment]
can i do this ?

**Comment by NayakNavin** [comment]
can i work on this ?

**Comment by AKMohite** [comment]
is root layout constraint layout??

**Comment by samyakjain** [comment]
Can I work on this?

**Comment by yangray1** [comment]
@samyakjain & Everyone else Hi guys, so in this PR, https://github.com/yangray1/Price-Scam-Detector/pull/4, the UI layout was fixed for every page ***except for the camera page*** (this is the activity_scan_barcode.xml)

If anyone wants to fix that page, feel free to do so!

**Left**: Nexus 5 API 28 device (camera view too large)   **Right**: Pixel 2 API 28 device (Correct sizing)
<img width="701" alt="Screen Shot 2019-10-07 at 6 55 40 PM" src="https://user-images.githubusercontent.com/39708793/66354868-2fbd0a00-e934-11e9-959b-a8909581d444.png">

**Comment by yangray1** [comment]
This issue has been fixed. Thanks guys!
